FROM nginx:alpine
# Lightweight, production-ready NGINX image

COPY default.conf /etc/nginx/conf.d/default.conf
# Replace default NGINX config with our own, so we can route frontend/backend correctly
